
name: magellan

services:
  - name: backend
    type: web
    env: node
    build:
      commands:
        - npm install
        - npm run build
    run:
      command: npm run start:prod
    ports:
      - 3000
    env_vars:
      - key: DATABASE_URL
        value: postgres://USER:PASSWORD@HOST/DBNAME
      - key: JWT_SECRET
        value: change-me-please
      - key: TAP_SECRET
        value: sk_test_xxx
      - key: TAP_MERCHANT_ID
        value: your_merchant_id
      - key: TAP_WEBHOOK_URL
        value: https://magellan.koyeb.app/api/payments/webhook
      - key: TAP_REDIRECT_URL
        value: https://magellan.koyeb.app/thankyou
      - key: PORT
        value: "3000"
